# This is a basic workflow to help you get started with Actions

name: download-data

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Download dataset
        run: wget https://www.internic.net/domain/root.zone

      # Runs a set of commands using the runners shell
      - name: Push data on github
        run: |
          git config --global user.name 'Romain'
          git config --global user.email 'romain.fontugne@gmail.com'
          git add .
          git commit -am 'new data'
          git push
